import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {validateEvents,filterEvents,safeSource,calculateIR,validateRules} from '../assets/core.js';
const data=JSON.parse(fs.readFileSync(new URL('../data/events.json',import.meta.url)));
const rules=JSON.parse(fs.readFileSync(new URL('../data/ir-2026.json',import.meta.url)));
test('published records require complete documentary evidence',()=>{assert.equal(validateEvents(data).length,data.events.length);for(const modify of [e=>e.verificationStatus='pending',e=>e.sources=[],e=>e.sources[0].url='javascript:alert(1)',e=>e.affected='',e=>e.legalStatus='Proposta']){const d=structuredClone(data);modify(d.events[0]);assert.throws(()=>validateEvents(d));}const duplicate=structuredClone(data);duplicate.events.push(duplicate.events[0]);assert.throws(()=>validateEvents(duplicate));});
test('sort and search regressions',()=>{assert.equal(filterEvents(data.events,{order:'asc'})[0].year,1922);assert.equal(filterEvents(data.events)[0].year,2026);assert.deepEqual(filterEvents(data.events,{q:'simplificacao'}),filterEvents(data.events,{q:' SIMPLIFICAÇÃO '}));assert.equal(filterEvents(data.events,{q:'no-such-record'}).length,0);assert.ok(filterEvents(data.events,{sphere:'Municipal'}).every(e=>e.spheres.includes('Municipal')));assert.equal(filterEvents([{...data.events[0],verificationStatus:'pending'}]).length,0);});
test('safe official URLs reject injection and lookalike hosts',()=>{for(const url of ['javascript:alert(1)','https://www.gov.br.evil.test/x','https://user:pass@www.gov.br/a','http://www.gov.br/a'])assert.equal(safeSource(url),false);assert.equal(safeSource('https://www2.camara.leg.br/x'),true);});
test('official Receita examples 3 and 4',()=>{const maria=calculateIR(5000,509.6,rules);assert.equal(maria.tax,0);assert.equal(maria.beforeReduction,312.89);assert.equal(maria.deduction,607.2);const rita=calculateIR(6000,649.6,rules);assert.equal(rita.base,5350.4);assert.equal(rita.beforeReduction,562.63);assert.equal(rita.reduction,179.75);assert.equal(rita.tax,382.88);});
test('reduction boundaries and no negative tax',()=>{assert.equal(calculateIR(0,0,rules).tax,0);assert.equal(calculateIR(5000,0,rules).tax,0);assert.equal(calculateIR(7350,0,rules).reduction,0);assert.equal(calculateIR(7350.01,0,rules).reduction,0);assert.equal(calculateIR(10000,0,rules).tax,1674.29);for(const income of [2428.8,2428.81,2826.65,2826.66,3751.05,3751.06,4664.68,4664.69,4999.99,5000.01,7349.99]){const r=calculateIR(income,0,rules);assert.ok(r.tax>=0&&r.reduction<=r.beforeReduction);}});
test('tax bracket edges after deductions',()=>{for(const [base,rate] of [[2428.8,0],[2428.81,.075],[2826.65,.075],[2826.66,.15],[3751.05,.15],[3751.06,.225],[4664.68,.225],[4664.69,.275]])assert.equal(calculateIR(base+1000,1000,rules).rate,rate);});
test('invalid amounts and invalid rules fail closed',()=>{for(const pair of [[-1,0],[NaN,0],[Infinity,0],[100,101],[100,-1]])assert.throws(()=>calculateIR(...pair,rules));const r=structuredClone(rules);r.brackets[1].upTo=-1;assert.throws(()=>validateRules(r));});
test('every original record accounted for without publishing it',()=>{const old=JSON.parse(fs.readFileSync(new URL('../_editorial/base-legada-nao-validada.json',import.meta.url)));const audit=JSON.parse(fs.readFileSync(new URL('../_editorial/revisao-legado.json',import.meta.url)));assert.equal(audit.records.length,old.length);assert.equal(audit.records.filter(r=>r.status==='duplicate').length,22);assert.equal(new Set(audit.records.map(r=>r.legacyIndex)).size,131);assert.equal(fs.existsSync(new URL('../tributos_brasil_1922_2025_ampliado.json',import.meta.url)),false);});

test('year filtering composes with topic and search',()=>{const result=filterEvents(data.events,{year:'2024',topic:'Salário e renda',q:'tabela'});assert.ok(result.length>0);assert.ok(result.every(e=>e.year===2024&&e.topic==='Salário e renda'));assert.equal(filterEvents(data.events,{year:'1800'}).length,0);});
test('legacy replacements resolve to published records',()=>{const audit=JSON.parse(fs.readFileSync(new URL('../_editorial/revisao-legado.json',import.meta.url)));for(const r of audit.records.filter(r=>r.replacementId))assert.ok(data.events.some(e=>e.id===r.replacementId),r.replacementId);const review=JSON.parse(fs.readFileSync(new URL('../_editorial/conferencia-ampliacao.json',import.meta.url)));for(const r of review){const e=data.events.find(e=>e.id===r.eventId);assert.equal(e.summary,r.claim);assert.equal(e.sources[0].url,r.url);assert.ok(/^[a-f0-9]{64}$/.test(r.sourceHtmlSha256));}});
